name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Hollow Knight version
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: Hollow Knight version
        required: true
        type: string
    secrets:
      BINARY_ARCHIVE_DEPLOY_KEY:
        required: true

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, macos, linux]
        ref: [main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout Binaries
        uses: actions/checkout@v4
        with:
          repository: hk-modding/hk-binary-archives
          ref: ${{ matrix.ref }}
          ssh-key: ${{ secrets.BINARY_ARCHIVE_DEPLOY_KEY }}
          sparse-checkout: |
            ${{ inputs.version }}/managed.${{ matrix.platform }}.tar.gz
          sparse-checkout-cone-mode: false
          path: ./hk-binary-archives
          
      - name: Unpack Archive
        run: |
          mkdir vanilla-15
          cd ./vanilla-15
          tar -xzf ../hk-binary-archives/${{ inputs.version }}/managed.${{ matrix.platform }}.tar.gz
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - name: Setup MSBuild
        run: |
          sudo apt-get install -y nuget mono-devel mono-xbuild
      
      - name: Build
        run: |
          dotnet restore
          dotnet build
      
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: build.${{ inputs.version }}.${{ matrix.platform }}
          path: ./out-15/
