name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag ID
        required: true
        type: string
      notes:
        description: Release notes
        type: string
      ms-version:
        description: MiniSavestates version
        required: true
        type: string
      hk-version:
        description: Hollow Knight version
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Get binaries from build run.
      - name: Build Binaries
        uses: ./.github/workflows/build.yaml
        with:
          version: ${{ inputs.hk-version }}
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Zip Artifacts
        run: |
            zip -jr minisavestates.windows.zip ./artifacts/build.${{ inputs.hk-version }}.windows/*
            zip -jr minisavestates.macos.zip ./artifacts/build.${{ inputs.hk-version }}.macos/*
            zip -jr minisavestates.linux.zip ./artifacts/build.${{ inputs.hk-version }}.linux/*
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Node Dependencies
        run: |
          npm install handlebars
      - name: Create Release Notes
        id: create-relnotes
        uses: actions/github-script@v7
        env:
          HK_VERSION: ${{ inputs.hk-version }}
          MS_VERSION: ${{ inputs.ms-version }}
          CHANGELOG: ${{ inputs.notes }}
        with:
          result-encoding: string
          script: |
            const script = require("./.github/workflows/create_relnotes.js");
            return await script();
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.create-relnotes.outputs.result }}
          tag_name: ${{ inputs.tag }}
          files: |
            ./minisavestates.windows.zip
            ./minisavestates.macos.zip
            ./minisavestates.linux.zip